//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/_Others/Input System/InputPlay.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlay : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlay()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlay"",
    ""maps"": [
        {
            ""name"": ""Preset01"",
            ""id"": ""65cc014e-6ae8-4afe-a739-05356880ef07"",
            ""actions"": [
                {
                    ""name"": ""Line A 01"",
                    ""type"": ""Button"",
                    ""id"": ""8f74dbc4-64a4-40d6-8adf-09d48d510918"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 02"",
                    ""type"": ""Button"",
                    ""id"": ""9f2c9349-7da7-42f4-8af1-8f15a27cb6a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 03"",
                    ""type"": ""Button"",
                    ""id"": ""41161cca-858a-44e1-950a-acaa05715761"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 04"",
                    ""type"": ""Button"",
                    ""id"": ""cb2328d3-52b3-4232-b5df-335d88ad8d14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 01"",
                    ""type"": ""Button"",
                    ""id"": ""2f7965da-5246-469d-acf3-edb98ff28847"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 02"",
                    ""type"": ""Button"",
                    ""id"": ""9eefb62e-10f3-4d21-afe9-47832a6bab19"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 03"",
                    ""type"": ""Button"",
                    ""id"": ""ebe58f30-ac29-4e59-bfdc-bc9738804811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 04"",
                    ""type"": ""Button"",
                    ""id"": ""82770b30-192d-4dd1-aae6-a1c6a628b2fb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - L"",
                    ""type"": ""Button"",
                    ""id"": ""199a2ee1-63a3-4294-a8a9-52df885498bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - R"",
                    ""type"": ""Button"",
                    ""id"": ""307fc084-0810-4ded-a096-d0c6d263f459"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ddb2d717-fb86-4654-8cbc-1f4fe56cc59a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baf2a132-c688-44ad-b9f6-5366d8da093d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6220284-f2a6-496d-a7d5-62170c1dcdc5"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85224b62-9c4b-4fb0-be4c-6bd238838d1d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ee15ba1-0338-4cfa-ade0-4cafba60b9e2"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""723d6f4a-f56c-4a92-bfac-7d50d9661905"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67f2eb69-698c-4526-8db6-ac38b2a6b560"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b9d1c38-5a65-4dc1-bf43-5a1b15c0844e"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45b162c1-28eb-4bff-b5a8-f69b6d8f4d53"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""409e1493-3d74-47c7-851b-97eb0df14cc0"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Preset02"",
            ""id"": ""15f931f2-c276-4d50-9ff2-2ffe5fa710e4"",
            ""actions"": [
                {
                    ""name"": ""Line A 01"",
                    ""type"": ""Button"",
                    ""id"": ""d6d04f90-0873-46d6-94f1-c038f27e40e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 02"",
                    ""type"": ""Button"",
                    ""id"": ""6fd5e7a5-0a6b-4e25-a9ca-6db093fe0d43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 03"",
                    ""type"": ""Button"",
                    ""id"": ""5c5ba3a5-5eed-4bb0-89a6-0edbc97c87b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 04"",
                    ""type"": ""Button"",
                    ""id"": ""4d079a9a-bd0e-4fa7-9dbb-eab83f185d21"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 01"",
                    ""type"": ""Button"",
                    ""id"": ""9431aa32-fdd0-4920-8d59-ff571abd2998"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 02"",
                    ""type"": ""Button"",
                    ""id"": ""e6f574c7-028e-471b-95bc-87aee66ff82f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 03"",
                    ""type"": ""Button"",
                    ""id"": ""604385b0-b8eb-48d9-93a0-cb0ab79e27e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 04"",
                    ""type"": ""Button"",
                    ""id"": ""71fdfac4-0a51-4e29-bc62-da44bbe65d40"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - L"",
                    ""type"": ""Button"",
                    ""id"": ""f2a3bc92-85e5-406d-8d0a-abe327dc8882"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - R"",
                    ""type"": ""Button"",
                    ""id"": ""cf5204d3-4f10-4c85-9289-00ab8d51fd43"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""357d28de-eab2-4b7d-b7d7-255b1aca254f"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8653b7f-771e-4491-8bf8-40721b53df54"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67d4cbc3-48df-441d-9ce2-d7b62c750132"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d496fff-0850-4630-bdbd-cf85981ecca6"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a1df820-bff9-4b33-8a2f-a5accd0842be"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32b89b55-c37a-4f16-8353-4a8eef00f76d"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c72fefb-0a09-4215-a874-7fbb530d06b5"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d138cd0-03bc-43bd-97e0-c7709e7d975e"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b45229b7-e758-4e38-b7cc-ce4efbfd2f45"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""35b4fe2c-df4a-4340-a716-8fa36d5fc2dc"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Preset03"",
            ""id"": ""f63d17a2-af6f-4ed9-b534-b9cd3d126596"",
            ""actions"": [
                {
                    ""name"": ""Line A 01"",
                    ""type"": ""Button"",
                    ""id"": ""d5a9fe86-dbca-4c93-b814-372fda571554"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 02"",
                    ""type"": ""Button"",
                    ""id"": ""247c2744-1233-44be-a678-604f0a0e8615"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 03"",
                    ""type"": ""Button"",
                    ""id"": ""bebc75b3-96b8-487c-82d6-a5e0d9b2db28"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 04"",
                    ""type"": ""Button"",
                    ""id"": ""ed1bc20a-7e07-4098-ad43-442ecaa07d37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 01"",
                    ""type"": ""Button"",
                    ""id"": ""b477a8f4-30a7-48db-8834-5d24300a2ff3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 02"",
                    ""type"": ""Button"",
                    ""id"": ""21fb529d-3573-4882-8f87-c4af6b83857b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 03"",
                    ""type"": ""Button"",
                    ""id"": ""97e27e10-59d2-43ff-b0ee-df3ffcfa565c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 04"",
                    ""type"": ""Button"",
                    ""id"": ""6efd570a-b579-4c56-801c-140b387f1be7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - L"",
                    ""type"": ""Button"",
                    ""id"": ""3f716dee-2d12-4282-90c2-53724d874fb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - R"",
                    ""type"": ""Button"",
                    ""id"": ""f41bbe4d-7500-4cfe-8bdb-9478d73faa4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""95665d4e-ad4a-49cc-951a-157a41d2cfac"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e822d557-9dec-4717-9f49-01199941572e"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab8c19a9-2787-4cc8-9718-a0c11c996edb"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31a13597-d8ab-41ed-a15b-b49ff5810a99"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a61a1000-9619-4d74-97e2-5d2f8a2d4d19"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33782c1e-2ac8-4484-9ddd-4ad77d94c2f5"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c5a2cd9-c6ea-4a17-830f-a1e79cca2e25"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9871009d-c1af-4da5-965b-9e35fa3343a6"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd120a51-b31b-4da8-b2d6-99b3a343afdf"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0341c6bb-deaf-40f2-9450-6ceee0e52bc6"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Preset04"",
            ""id"": ""d42cc8bf-64a4-41d1-a113-f3838949f47f"",
            ""actions"": [
                {
                    ""name"": ""Line A 01"",
                    ""type"": ""Button"",
                    ""id"": ""81f48420-caeb-45fe-a500-ec3562730730"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 02"",
                    ""type"": ""Button"",
                    ""id"": ""ff96e5d1-c360-4192-b16d-b968a292620f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 03"",
                    ""type"": ""Button"",
                    ""id"": ""c92702c9-72fd-426c-a945-6661c664c124"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 04"",
                    ""type"": ""Button"",
                    ""id"": ""836ab537-0d63-43d0-80f0-3b79fdd0f47c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 01"",
                    ""type"": ""Button"",
                    ""id"": ""cd308986-3978-4597-abf8-cf30d0ccf49c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 02"",
                    ""type"": ""Button"",
                    ""id"": ""792103d0-9bc8-4916-ac0f-e405ccf5f992"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 03"",
                    ""type"": ""Button"",
                    ""id"": ""94e8f977-92ed-4bfb-bf2e-4f65db687d62"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 04"",
                    ""type"": ""Button"",
                    ""id"": ""9670ab7a-9b7e-411f-b612-9c84f21e5723"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - L"",
                    ""type"": ""Button"",
                    ""id"": ""d498e089-de42-48e8-9d9b-99d974182f4f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - R"",
                    ""type"": ""Button"",
                    ""id"": ""28ea69b8-3def-406c-afc2-ef5b55487e4d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""309cbfc1-eddd-429c-b747-c5f7f0210715"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""881d429f-471e-4824-b9fe-215256579ba9"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbf06ec2-63bf-4dbb-9e90-65555db10f25"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07c7d4a3-6398-446a-a9b6-079a8da709f5"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49eb3ef5-2485-48cf-b958-021fcae89cf1"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4270127f-44ca-4401-87c2-f801c531066e"",
                    ""path"": ""<Keyboard>/comma"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c969c36-8ce2-4b82-a3e2-a5c91ba563a0"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea20f52b-8c9d-4bd1-87bf-fa5ebfd590bf"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de75ad4a-5b2e-48ae-a1b9-29865ab1dac8"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7462f12-6f02-4e51-9379-7806bd431084"",
                    ""path"": ""<Keyboard>/rightShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""User"",
            ""id"": ""c783049e-d178-4d31-b938-83db8460abec"",
            ""actions"": [
                {
                    ""name"": ""Line A 01"",
                    ""type"": ""Button"",
                    ""id"": ""8f416c6c-672a-4e72-aa7f-4f4a147f859f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 02"",
                    ""type"": ""Button"",
                    ""id"": ""efb11a1c-ddc7-403c-b82c-3ed5170041c5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 03"",
                    ""type"": ""Button"",
                    ""id"": ""14565b94-1eba-4535-b569-1c6bd60340f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line A 04"",
                    ""type"": ""Button"",
                    ""id"": ""5c1e7d49-8eb4-42c0-9916-1bc77b0572bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 01"",
                    ""type"": ""Button"",
                    ""id"": ""24ceb283-22eb-4a89-a48a-954c2bc1b81a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 02"",
                    ""type"": ""Button"",
                    ""id"": ""37a23919-e48e-492a-8ef4-f8f59d1e49c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 03"",
                    ""type"": ""Button"",
                    ""id"": ""10dd414b-057d-480a-88dd-4d174bbb6d6b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Line B 04"",
                    ""type"": ""Button"",
                    ""id"": ""201f8b24-ae4b-4d86-8d3c-a9992811dcb9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - L"",
                    ""type"": ""Button"",
                    ""id"": ""068a0e24-f3d3-48ee-addf-2dadb48b6a4c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Side - R"",
                    ""type"": ""Button"",
                    ""id"": ""898a6dc6-2713-43cc-9726-94e98da25f23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3e2a3dfe-7ee4-4c7d-95b6-4ce92d395712"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""71a4a9c5-4103-4211-ac15-ee6dbc027051"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ed3d236-c87c-4b89-86ca-a5a9a00231e1"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""218c9055-57c1-4212-8937-f32c490dd1eb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8870f3db-5708-4cf1-8217-c88a1b953759"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6f96c70-582f-4312-97a3-515e9312a439"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5b7188a-0378-4f22-ac21-2ba1a1bd127f"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line B 04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc82bdaa-9784-4dd5-9346-4c7a99b45952"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - L"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""206e9005-ebad-439d-bb9f-dc6f4d33b327"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Side - R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d9121ad-56fc-4d7e-b7d8-6cda1e5eb16e"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Line A 01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Preset01
        m_Preset01 = asset.FindActionMap("Preset01", throwIfNotFound: true);
        m_Preset01_LineA01 = m_Preset01.FindAction("Line A 01", throwIfNotFound: true);
        m_Preset01_LineA02 = m_Preset01.FindAction("Line A 02", throwIfNotFound: true);
        m_Preset01_LineA03 = m_Preset01.FindAction("Line A 03", throwIfNotFound: true);
        m_Preset01_LineA04 = m_Preset01.FindAction("Line A 04", throwIfNotFound: true);
        m_Preset01_LineB01 = m_Preset01.FindAction("Line B 01", throwIfNotFound: true);
        m_Preset01_LineB02 = m_Preset01.FindAction("Line B 02", throwIfNotFound: true);
        m_Preset01_LineB03 = m_Preset01.FindAction("Line B 03", throwIfNotFound: true);
        m_Preset01_LineB04 = m_Preset01.FindAction("Line B 04", throwIfNotFound: true);
        m_Preset01_SideL = m_Preset01.FindAction("Side - L", throwIfNotFound: true);
        m_Preset01_SideR = m_Preset01.FindAction("Side - R", throwIfNotFound: true);
        // Preset02
        m_Preset02 = asset.FindActionMap("Preset02", throwIfNotFound: true);
        m_Preset02_LineA01 = m_Preset02.FindAction("Line A 01", throwIfNotFound: true);
        m_Preset02_LineA02 = m_Preset02.FindAction("Line A 02", throwIfNotFound: true);
        m_Preset02_LineA03 = m_Preset02.FindAction("Line A 03", throwIfNotFound: true);
        m_Preset02_LineA04 = m_Preset02.FindAction("Line A 04", throwIfNotFound: true);
        m_Preset02_LineB01 = m_Preset02.FindAction("Line B 01", throwIfNotFound: true);
        m_Preset02_LineB02 = m_Preset02.FindAction("Line B 02", throwIfNotFound: true);
        m_Preset02_LineB03 = m_Preset02.FindAction("Line B 03", throwIfNotFound: true);
        m_Preset02_LineB04 = m_Preset02.FindAction("Line B 04", throwIfNotFound: true);
        m_Preset02_SideL = m_Preset02.FindAction("Side - L", throwIfNotFound: true);
        m_Preset02_SideR = m_Preset02.FindAction("Side - R", throwIfNotFound: true);
        // Preset03
        m_Preset03 = asset.FindActionMap("Preset03", throwIfNotFound: true);
        m_Preset03_LineA01 = m_Preset03.FindAction("Line A 01", throwIfNotFound: true);
        m_Preset03_LineA02 = m_Preset03.FindAction("Line A 02", throwIfNotFound: true);
        m_Preset03_LineA03 = m_Preset03.FindAction("Line A 03", throwIfNotFound: true);
        m_Preset03_LineA04 = m_Preset03.FindAction("Line A 04", throwIfNotFound: true);
        m_Preset03_LineB01 = m_Preset03.FindAction("Line B 01", throwIfNotFound: true);
        m_Preset03_LineB02 = m_Preset03.FindAction("Line B 02", throwIfNotFound: true);
        m_Preset03_LineB03 = m_Preset03.FindAction("Line B 03", throwIfNotFound: true);
        m_Preset03_LineB04 = m_Preset03.FindAction("Line B 04", throwIfNotFound: true);
        m_Preset03_SideL = m_Preset03.FindAction("Side - L", throwIfNotFound: true);
        m_Preset03_SideR = m_Preset03.FindAction("Side - R", throwIfNotFound: true);
        // Preset04
        m_Preset04 = asset.FindActionMap("Preset04", throwIfNotFound: true);
        m_Preset04_LineA01 = m_Preset04.FindAction("Line A 01", throwIfNotFound: true);
        m_Preset04_LineA02 = m_Preset04.FindAction("Line A 02", throwIfNotFound: true);
        m_Preset04_LineA03 = m_Preset04.FindAction("Line A 03", throwIfNotFound: true);
        m_Preset04_LineA04 = m_Preset04.FindAction("Line A 04", throwIfNotFound: true);
        m_Preset04_LineB01 = m_Preset04.FindAction("Line B 01", throwIfNotFound: true);
        m_Preset04_LineB02 = m_Preset04.FindAction("Line B 02", throwIfNotFound: true);
        m_Preset04_LineB03 = m_Preset04.FindAction("Line B 03", throwIfNotFound: true);
        m_Preset04_LineB04 = m_Preset04.FindAction("Line B 04", throwIfNotFound: true);
        m_Preset04_SideL = m_Preset04.FindAction("Side - L", throwIfNotFound: true);
        m_Preset04_SideR = m_Preset04.FindAction("Side - R", throwIfNotFound: true);
        // User
        m_User = asset.FindActionMap("User", throwIfNotFound: true);
        m_User_LineA01 = m_User.FindAction("Line A 01", throwIfNotFound: true);
        m_User_LineA02 = m_User.FindAction("Line A 02", throwIfNotFound: true);
        m_User_LineA03 = m_User.FindAction("Line A 03", throwIfNotFound: true);
        m_User_LineA04 = m_User.FindAction("Line A 04", throwIfNotFound: true);
        m_User_LineB01 = m_User.FindAction("Line B 01", throwIfNotFound: true);
        m_User_LineB02 = m_User.FindAction("Line B 02", throwIfNotFound: true);
        m_User_LineB03 = m_User.FindAction("Line B 03", throwIfNotFound: true);
        m_User_LineB04 = m_User.FindAction("Line B 04", throwIfNotFound: true);
        m_User_SideL = m_User.FindAction("Side - L", throwIfNotFound: true);
        m_User_SideR = m_User.FindAction("Side - R", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Preset01
    private readonly InputActionMap m_Preset01;
    private IPreset01Actions m_Preset01ActionsCallbackInterface;
    private readonly InputAction m_Preset01_LineA01;
    private readonly InputAction m_Preset01_LineA02;
    private readonly InputAction m_Preset01_LineA03;
    private readonly InputAction m_Preset01_LineA04;
    private readonly InputAction m_Preset01_LineB01;
    private readonly InputAction m_Preset01_LineB02;
    private readonly InputAction m_Preset01_LineB03;
    private readonly InputAction m_Preset01_LineB04;
    private readonly InputAction m_Preset01_SideL;
    private readonly InputAction m_Preset01_SideR;
    public struct Preset01Actions
    {
        private @InputPlay m_Wrapper;
        public Preset01Actions(@InputPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @LineA01 => m_Wrapper.m_Preset01_LineA01;
        public InputAction @LineA02 => m_Wrapper.m_Preset01_LineA02;
        public InputAction @LineA03 => m_Wrapper.m_Preset01_LineA03;
        public InputAction @LineA04 => m_Wrapper.m_Preset01_LineA04;
        public InputAction @LineB01 => m_Wrapper.m_Preset01_LineB01;
        public InputAction @LineB02 => m_Wrapper.m_Preset01_LineB02;
        public InputAction @LineB03 => m_Wrapper.m_Preset01_LineB03;
        public InputAction @LineB04 => m_Wrapper.m_Preset01_LineB04;
        public InputAction @SideL => m_Wrapper.m_Preset01_SideL;
        public InputAction @SideR => m_Wrapper.m_Preset01_SideR;
        public InputActionMap Get() { return m_Wrapper.m_Preset01; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Preset01Actions set) { return set.Get(); }
        public void SetCallbacks(IPreset01Actions instance)
        {
            if (m_Wrapper.m_Preset01ActionsCallbackInterface != null)
            {
                @LineA01.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA01;
                @LineA01.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA01;
                @LineA01.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA01;
                @LineA02.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA02;
                @LineA02.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA02;
                @LineA02.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA02;
                @LineA03.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA03;
                @LineA03.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA03;
                @LineA03.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA03;
                @LineA04.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA04;
                @LineA04.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA04;
                @LineA04.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineA04;
                @LineB01.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB01;
                @LineB01.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB01;
                @LineB01.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB01;
                @LineB02.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB02;
                @LineB02.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB02;
                @LineB02.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB02;
                @LineB03.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB03;
                @LineB03.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB03;
                @LineB03.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB03;
                @LineB04.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB04;
                @LineB04.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB04;
                @LineB04.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnLineB04;
                @SideL.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideL;
                @SideL.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideL;
                @SideL.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideL;
                @SideR.started -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideR;
                @SideR.performed -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideR;
                @SideR.canceled -= m_Wrapper.m_Preset01ActionsCallbackInterface.OnSideR;
            }
            m_Wrapper.m_Preset01ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LineA01.started += instance.OnLineA01;
                @LineA01.performed += instance.OnLineA01;
                @LineA01.canceled += instance.OnLineA01;
                @LineA02.started += instance.OnLineA02;
                @LineA02.performed += instance.OnLineA02;
                @LineA02.canceled += instance.OnLineA02;
                @LineA03.started += instance.OnLineA03;
                @LineA03.performed += instance.OnLineA03;
                @LineA03.canceled += instance.OnLineA03;
                @LineA04.started += instance.OnLineA04;
                @LineA04.performed += instance.OnLineA04;
                @LineA04.canceled += instance.OnLineA04;
                @LineB01.started += instance.OnLineB01;
                @LineB01.performed += instance.OnLineB01;
                @LineB01.canceled += instance.OnLineB01;
                @LineB02.started += instance.OnLineB02;
                @LineB02.performed += instance.OnLineB02;
                @LineB02.canceled += instance.OnLineB02;
                @LineB03.started += instance.OnLineB03;
                @LineB03.performed += instance.OnLineB03;
                @LineB03.canceled += instance.OnLineB03;
                @LineB04.started += instance.OnLineB04;
                @LineB04.performed += instance.OnLineB04;
                @LineB04.canceled += instance.OnLineB04;
                @SideL.started += instance.OnSideL;
                @SideL.performed += instance.OnSideL;
                @SideL.canceled += instance.OnSideL;
                @SideR.started += instance.OnSideR;
                @SideR.performed += instance.OnSideR;
                @SideR.canceled += instance.OnSideR;
            }
        }
    }
    public Preset01Actions @Preset01 => new Preset01Actions(this);

    // Preset02
    private readonly InputActionMap m_Preset02;
    private IPreset02Actions m_Preset02ActionsCallbackInterface;
    private readonly InputAction m_Preset02_LineA01;
    private readonly InputAction m_Preset02_LineA02;
    private readonly InputAction m_Preset02_LineA03;
    private readonly InputAction m_Preset02_LineA04;
    private readonly InputAction m_Preset02_LineB01;
    private readonly InputAction m_Preset02_LineB02;
    private readonly InputAction m_Preset02_LineB03;
    private readonly InputAction m_Preset02_LineB04;
    private readonly InputAction m_Preset02_SideL;
    private readonly InputAction m_Preset02_SideR;
    public struct Preset02Actions
    {
        private @InputPlay m_Wrapper;
        public Preset02Actions(@InputPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @LineA01 => m_Wrapper.m_Preset02_LineA01;
        public InputAction @LineA02 => m_Wrapper.m_Preset02_LineA02;
        public InputAction @LineA03 => m_Wrapper.m_Preset02_LineA03;
        public InputAction @LineA04 => m_Wrapper.m_Preset02_LineA04;
        public InputAction @LineB01 => m_Wrapper.m_Preset02_LineB01;
        public InputAction @LineB02 => m_Wrapper.m_Preset02_LineB02;
        public InputAction @LineB03 => m_Wrapper.m_Preset02_LineB03;
        public InputAction @LineB04 => m_Wrapper.m_Preset02_LineB04;
        public InputAction @SideL => m_Wrapper.m_Preset02_SideL;
        public InputAction @SideR => m_Wrapper.m_Preset02_SideR;
        public InputActionMap Get() { return m_Wrapper.m_Preset02; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Preset02Actions set) { return set.Get(); }
        public void SetCallbacks(IPreset02Actions instance)
        {
            if (m_Wrapper.m_Preset02ActionsCallbackInterface != null)
            {
                @LineA01.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA01;
                @LineA01.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA01;
                @LineA01.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA01;
                @LineA02.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA02;
                @LineA02.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA02;
                @LineA02.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA02;
                @LineA03.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA03;
                @LineA03.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA03;
                @LineA03.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA03;
                @LineA04.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA04;
                @LineA04.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA04;
                @LineA04.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineA04;
                @LineB01.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB01;
                @LineB01.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB01;
                @LineB01.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB01;
                @LineB02.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB02;
                @LineB02.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB02;
                @LineB02.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB02;
                @LineB03.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB03;
                @LineB03.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB03;
                @LineB03.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB03;
                @LineB04.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB04;
                @LineB04.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB04;
                @LineB04.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnLineB04;
                @SideL.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideL;
                @SideL.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideL;
                @SideL.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideL;
                @SideR.started -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideR;
                @SideR.performed -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideR;
                @SideR.canceled -= m_Wrapper.m_Preset02ActionsCallbackInterface.OnSideR;
            }
            m_Wrapper.m_Preset02ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LineA01.started += instance.OnLineA01;
                @LineA01.performed += instance.OnLineA01;
                @LineA01.canceled += instance.OnLineA01;
                @LineA02.started += instance.OnLineA02;
                @LineA02.performed += instance.OnLineA02;
                @LineA02.canceled += instance.OnLineA02;
                @LineA03.started += instance.OnLineA03;
                @LineA03.performed += instance.OnLineA03;
                @LineA03.canceled += instance.OnLineA03;
                @LineA04.started += instance.OnLineA04;
                @LineA04.performed += instance.OnLineA04;
                @LineA04.canceled += instance.OnLineA04;
                @LineB01.started += instance.OnLineB01;
                @LineB01.performed += instance.OnLineB01;
                @LineB01.canceled += instance.OnLineB01;
                @LineB02.started += instance.OnLineB02;
                @LineB02.performed += instance.OnLineB02;
                @LineB02.canceled += instance.OnLineB02;
                @LineB03.started += instance.OnLineB03;
                @LineB03.performed += instance.OnLineB03;
                @LineB03.canceled += instance.OnLineB03;
                @LineB04.started += instance.OnLineB04;
                @LineB04.performed += instance.OnLineB04;
                @LineB04.canceled += instance.OnLineB04;
                @SideL.started += instance.OnSideL;
                @SideL.performed += instance.OnSideL;
                @SideL.canceled += instance.OnSideL;
                @SideR.started += instance.OnSideR;
                @SideR.performed += instance.OnSideR;
                @SideR.canceled += instance.OnSideR;
            }
        }
    }
    public Preset02Actions @Preset02 => new Preset02Actions(this);

    // Preset03
    private readonly InputActionMap m_Preset03;
    private IPreset03Actions m_Preset03ActionsCallbackInterface;
    private readonly InputAction m_Preset03_LineA01;
    private readonly InputAction m_Preset03_LineA02;
    private readonly InputAction m_Preset03_LineA03;
    private readonly InputAction m_Preset03_LineA04;
    private readonly InputAction m_Preset03_LineB01;
    private readonly InputAction m_Preset03_LineB02;
    private readonly InputAction m_Preset03_LineB03;
    private readonly InputAction m_Preset03_LineB04;
    private readonly InputAction m_Preset03_SideL;
    private readonly InputAction m_Preset03_SideR;
    public struct Preset03Actions
    {
        private @InputPlay m_Wrapper;
        public Preset03Actions(@InputPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @LineA01 => m_Wrapper.m_Preset03_LineA01;
        public InputAction @LineA02 => m_Wrapper.m_Preset03_LineA02;
        public InputAction @LineA03 => m_Wrapper.m_Preset03_LineA03;
        public InputAction @LineA04 => m_Wrapper.m_Preset03_LineA04;
        public InputAction @LineB01 => m_Wrapper.m_Preset03_LineB01;
        public InputAction @LineB02 => m_Wrapper.m_Preset03_LineB02;
        public InputAction @LineB03 => m_Wrapper.m_Preset03_LineB03;
        public InputAction @LineB04 => m_Wrapper.m_Preset03_LineB04;
        public InputAction @SideL => m_Wrapper.m_Preset03_SideL;
        public InputAction @SideR => m_Wrapper.m_Preset03_SideR;
        public InputActionMap Get() { return m_Wrapper.m_Preset03; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Preset03Actions set) { return set.Get(); }
        public void SetCallbacks(IPreset03Actions instance)
        {
            if (m_Wrapper.m_Preset03ActionsCallbackInterface != null)
            {
                @LineA01.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA01;
                @LineA01.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA01;
                @LineA01.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA01;
                @LineA02.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA02;
                @LineA02.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA02;
                @LineA02.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA02;
                @LineA03.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA03;
                @LineA03.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA03;
                @LineA03.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA03;
                @LineA04.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA04;
                @LineA04.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA04;
                @LineA04.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineA04;
                @LineB01.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB01;
                @LineB01.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB01;
                @LineB01.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB01;
                @LineB02.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB02;
                @LineB02.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB02;
                @LineB02.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB02;
                @LineB03.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB03;
                @LineB03.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB03;
                @LineB03.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB03;
                @LineB04.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB04;
                @LineB04.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB04;
                @LineB04.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnLineB04;
                @SideL.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideL;
                @SideL.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideL;
                @SideL.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideL;
                @SideR.started -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideR;
                @SideR.performed -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideR;
                @SideR.canceled -= m_Wrapper.m_Preset03ActionsCallbackInterface.OnSideR;
            }
            m_Wrapper.m_Preset03ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LineA01.started += instance.OnLineA01;
                @LineA01.performed += instance.OnLineA01;
                @LineA01.canceled += instance.OnLineA01;
                @LineA02.started += instance.OnLineA02;
                @LineA02.performed += instance.OnLineA02;
                @LineA02.canceled += instance.OnLineA02;
                @LineA03.started += instance.OnLineA03;
                @LineA03.performed += instance.OnLineA03;
                @LineA03.canceled += instance.OnLineA03;
                @LineA04.started += instance.OnLineA04;
                @LineA04.performed += instance.OnLineA04;
                @LineA04.canceled += instance.OnLineA04;
                @LineB01.started += instance.OnLineB01;
                @LineB01.performed += instance.OnLineB01;
                @LineB01.canceled += instance.OnLineB01;
                @LineB02.started += instance.OnLineB02;
                @LineB02.performed += instance.OnLineB02;
                @LineB02.canceled += instance.OnLineB02;
                @LineB03.started += instance.OnLineB03;
                @LineB03.performed += instance.OnLineB03;
                @LineB03.canceled += instance.OnLineB03;
                @LineB04.started += instance.OnLineB04;
                @LineB04.performed += instance.OnLineB04;
                @LineB04.canceled += instance.OnLineB04;
                @SideL.started += instance.OnSideL;
                @SideL.performed += instance.OnSideL;
                @SideL.canceled += instance.OnSideL;
                @SideR.started += instance.OnSideR;
                @SideR.performed += instance.OnSideR;
                @SideR.canceled += instance.OnSideR;
            }
        }
    }
    public Preset03Actions @Preset03 => new Preset03Actions(this);

    // Preset04
    private readonly InputActionMap m_Preset04;
    private IPreset04Actions m_Preset04ActionsCallbackInterface;
    private readonly InputAction m_Preset04_LineA01;
    private readonly InputAction m_Preset04_LineA02;
    private readonly InputAction m_Preset04_LineA03;
    private readonly InputAction m_Preset04_LineA04;
    private readonly InputAction m_Preset04_LineB01;
    private readonly InputAction m_Preset04_LineB02;
    private readonly InputAction m_Preset04_LineB03;
    private readonly InputAction m_Preset04_LineB04;
    private readonly InputAction m_Preset04_SideL;
    private readonly InputAction m_Preset04_SideR;
    public struct Preset04Actions
    {
        private @InputPlay m_Wrapper;
        public Preset04Actions(@InputPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @LineA01 => m_Wrapper.m_Preset04_LineA01;
        public InputAction @LineA02 => m_Wrapper.m_Preset04_LineA02;
        public InputAction @LineA03 => m_Wrapper.m_Preset04_LineA03;
        public InputAction @LineA04 => m_Wrapper.m_Preset04_LineA04;
        public InputAction @LineB01 => m_Wrapper.m_Preset04_LineB01;
        public InputAction @LineB02 => m_Wrapper.m_Preset04_LineB02;
        public InputAction @LineB03 => m_Wrapper.m_Preset04_LineB03;
        public InputAction @LineB04 => m_Wrapper.m_Preset04_LineB04;
        public InputAction @SideL => m_Wrapper.m_Preset04_SideL;
        public InputAction @SideR => m_Wrapper.m_Preset04_SideR;
        public InputActionMap Get() { return m_Wrapper.m_Preset04; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Preset04Actions set) { return set.Get(); }
        public void SetCallbacks(IPreset04Actions instance)
        {
            if (m_Wrapper.m_Preset04ActionsCallbackInterface != null)
            {
                @LineA01.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA01;
                @LineA01.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA01;
                @LineA01.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA01;
                @LineA02.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA02;
                @LineA02.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA02;
                @LineA02.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA02;
                @LineA03.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA03;
                @LineA03.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA03;
                @LineA03.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA03;
                @LineA04.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA04;
                @LineA04.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA04;
                @LineA04.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineA04;
                @LineB01.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB01;
                @LineB01.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB01;
                @LineB01.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB01;
                @LineB02.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB02;
                @LineB02.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB02;
                @LineB02.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB02;
                @LineB03.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB03;
                @LineB03.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB03;
                @LineB03.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB03;
                @LineB04.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB04;
                @LineB04.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB04;
                @LineB04.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnLineB04;
                @SideL.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideL;
                @SideL.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideL;
                @SideL.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideL;
                @SideR.started -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideR;
                @SideR.performed -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideR;
                @SideR.canceled -= m_Wrapper.m_Preset04ActionsCallbackInterface.OnSideR;
            }
            m_Wrapper.m_Preset04ActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LineA01.started += instance.OnLineA01;
                @LineA01.performed += instance.OnLineA01;
                @LineA01.canceled += instance.OnLineA01;
                @LineA02.started += instance.OnLineA02;
                @LineA02.performed += instance.OnLineA02;
                @LineA02.canceled += instance.OnLineA02;
                @LineA03.started += instance.OnLineA03;
                @LineA03.performed += instance.OnLineA03;
                @LineA03.canceled += instance.OnLineA03;
                @LineA04.started += instance.OnLineA04;
                @LineA04.performed += instance.OnLineA04;
                @LineA04.canceled += instance.OnLineA04;
                @LineB01.started += instance.OnLineB01;
                @LineB01.performed += instance.OnLineB01;
                @LineB01.canceled += instance.OnLineB01;
                @LineB02.started += instance.OnLineB02;
                @LineB02.performed += instance.OnLineB02;
                @LineB02.canceled += instance.OnLineB02;
                @LineB03.started += instance.OnLineB03;
                @LineB03.performed += instance.OnLineB03;
                @LineB03.canceled += instance.OnLineB03;
                @LineB04.started += instance.OnLineB04;
                @LineB04.performed += instance.OnLineB04;
                @LineB04.canceled += instance.OnLineB04;
                @SideL.started += instance.OnSideL;
                @SideL.performed += instance.OnSideL;
                @SideL.canceled += instance.OnSideL;
                @SideR.started += instance.OnSideR;
                @SideR.performed += instance.OnSideR;
                @SideR.canceled += instance.OnSideR;
            }
        }
    }
    public Preset04Actions @Preset04 => new Preset04Actions(this);

    // User
    private readonly InputActionMap m_User;
    private IUserActions m_UserActionsCallbackInterface;
    private readonly InputAction m_User_LineA01;
    private readonly InputAction m_User_LineA02;
    private readonly InputAction m_User_LineA03;
    private readonly InputAction m_User_LineA04;
    private readonly InputAction m_User_LineB01;
    private readonly InputAction m_User_LineB02;
    private readonly InputAction m_User_LineB03;
    private readonly InputAction m_User_LineB04;
    private readonly InputAction m_User_SideL;
    private readonly InputAction m_User_SideR;
    public struct UserActions
    {
        private @InputPlay m_Wrapper;
        public UserActions(@InputPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @LineA01 => m_Wrapper.m_User_LineA01;
        public InputAction @LineA02 => m_Wrapper.m_User_LineA02;
        public InputAction @LineA03 => m_Wrapper.m_User_LineA03;
        public InputAction @LineA04 => m_Wrapper.m_User_LineA04;
        public InputAction @LineB01 => m_Wrapper.m_User_LineB01;
        public InputAction @LineB02 => m_Wrapper.m_User_LineB02;
        public InputAction @LineB03 => m_Wrapper.m_User_LineB03;
        public InputAction @LineB04 => m_Wrapper.m_User_LineB04;
        public InputAction @SideL => m_Wrapper.m_User_SideL;
        public InputAction @SideR => m_Wrapper.m_User_SideR;
        public InputActionMap Get() { return m_Wrapper.m_User; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UserActions set) { return set.Get(); }
        public void SetCallbacks(IUserActions instance)
        {
            if (m_Wrapper.m_UserActionsCallbackInterface != null)
            {
                @LineA01.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA01;
                @LineA01.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA01;
                @LineA01.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA01;
                @LineA02.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA02;
                @LineA02.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA02;
                @LineA02.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA02;
                @LineA03.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA03;
                @LineA03.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA03;
                @LineA03.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA03;
                @LineA04.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA04;
                @LineA04.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA04;
                @LineA04.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineA04;
                @LineB01.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB01;
                @LineB01.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB01;
                @LineB01.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB01;
                @LineB02.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB02;
                @LineB02.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB02;
                @LineB02.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB02;
                @LineB03.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB03;
                @LineB03.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB03;
                @LineB03.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB03;
                @LineB04.started -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB04;
                @LineB04.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB04;
                @LineB04.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnLineB04;
                @SideL.started -= m_Wrapper.m_UserActionsCallbackInterface.OnSideL;
                @SideL.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnSideL;
                @SideL.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnSideL;
                @SideR.started -= m_Wrapper.m_UserActionsCallbackInterface.OnSideR;
                @SideR.performed -= m_Wrapper.m_UserActionsCallbackInterface.OnSideR;
                @SideR.canceled -= m_Wrapper.m_UserActionsCallbackInterface.OnSideR;
            }
            m_Wrapper.m_UserActionsCallbackInterface = instance;
            if (instance != null)
            {
                @LineA01.started += instance.OnLineA01;
                @LineA01.performed += instance.OnLineA01;
                @LineA01.canceled += instance.OnLineA01;
                @LineA02.started += instance.OnLineA02;
                @LineA02.performed += instance.OnLineA02;
                @LineA02.canceled += instance.OnLineA02;
                @LineA03.started += instance.OnLineA03;
                @LineA03.performed += instance.OnLineA03;
                @LineA03.canceled += instance.OnLineA03;
                @LineA04.started += instance.OnLineA04;
                @LineA04.performed += instance.OnLineA04;
                @LineA04.canceled += instance.OnLineA04;
                @LineB01.started += instance.OnLineB01;
                @LineB01.performed += instance.OnLineB01;
                @LineB01.canceled += instance.OnLineB01;
                @LineB02.started += instance.OnLineB02;
                @LineB02.performed += instance.OnLineB02;
                @LineB02.canceled += instance.OnLineB02;
                @LineB03.started += instance.OnLineB03;
                @LineB03.performed += instance.OnLineB03;
                @LineB03.canceled += instance.OnLineB03;
                @LineB04.started += instance.OnLineB04;
                @LineB04.performed += instance.OnLineB04;
                @LineB04.canceled += instance.OnLineB04;
                @SideL.started += instance.OnSideL;
                @SideL.performed += instance.OnSideL;
                @SideL.canceled += instance.OnSideL;
                @SideR.started += instance.OnSideR;
                @SideR.performed += instance.OnSideR;
                @SideR.canceled += instance.OnSideR;
            }
        }
    }
    public UserActions @User => new UserActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPreset01Actions
    {
        void OnLineA01(InputAction.CallbackContext context);
        void OnLineA02(InputAction.CallbackContext context);
        void OnLineA03(InputAction.CallbackContext context);
        void OnLineA04(InputAction.CallbackContext context);
        void OnLineB01(InputAction.CallbackContext context);
        void OnLineB02(InputAction.CallbackContext context);
        void OnLineB03(InputAction.CallbackContext context);
        void OnLineB04(InputAction.CallbackContext context);
        void OnSideL(InputAction.CallbackContext context);
        void OnSideR(InputAction.CallbackContext context);
    }
    public interface IPreset02Actions
    {
        void OnLineA01(InputAction.CallbackContext context);
        void OnLineA02(InputAction.CallbackContext context);
        void OnLineA03(InputAction.CallbackContext context);
        void OnLineA04(InputAction.CallbackContext context);
        void OnLineB01(InputAction.CallbackContext context);
        void OnLineB02(InputAction.CallbackContext context);
        void OnLineB03(InputAction.CallbackContext context);
        void OnLineB04(InputAction.CallbackContext context);
        void OnSideL(InputAction.CallbackContext context);
        void OnSideR(InputAction.CallbackContext context);
    }
    public interface IPreset03Actions
    {
        void OnLineA01(InputAction.CallbackContext context);
        void OnLineA02(InputAction.CallbackContext context);
        void OnLineA03(InputAction.CallbackContext context);
        void OnLineA04(InputAction.CallbackContext context);
        void OnLineB01(InputAction.CallbackContext context);
        void OnLineB02(InputAction.CallbackContext context);
        void OnLineB03(InputAction.CallbackContext context);
        void OnLineB04(InputAction.CallbackContext context);
        void OnSideL(InputAction.CallbackContext context);
        void OnSideR(InputAction.CallbackContext context);
    }
    public interface IPreset04Actions
    {
        void OnLineA01(InputAction.CallbackContext context);
        void OnLineA02(InputAction.CallbackContext context);
        void OnLineA03(InputAction.CallbackContext context);
        void OnLineA04(InputAction.CallbackContext context);
        void OnLineB01(InputAction.CallbackContext context);
        void OnLineB02(InputAction.CallbackContext context);
        void OnLineB03(InputAction.CallbackContext context);
        void OnLineB04(InputAction.CallbackContext context);
        void OnSideL(InputAction.CallbackContext context);
        void OnSideR(InputAction.CallbackContext context);
    }
    public interface IUserActions
    {
        void OnLineA01(InputAction.CallbackContext context);
        void OnLineA02(InputAction.CallbackContext context);
        void OnLineA03(InputAction.CallbackContext context);
        void OnLineA04(InputAction.CallbackContext context);
        void OnLineB01(InputAction.CallbackContext context);
        void OnLineB02(InputAction.CallbackContext context);
        void OnLineB03(InputAction.CallbackContext context);
        void OnLineB04(InputAction.CallbackContext context);
        void OnSideL(InputAction.CallbackContext context);
        void OnSideR(InputAction.CallbackContext context);
    }
}
